
# import banana_dev as banana
import base64
from io import BytesIO
from PIL import Image
import requests
from flask import Flask, request
import os
import telebot
import matplotlib.pyplot as plt
import numpy as np
import requests
import random
# os.environ['BOT_TOKEN'] = '6286216473:AAHVgHBtEwqztI0939BbENwoUyugh2vuBlc'
os.environ['BOT_TOKEN'] = '6118467837:AAHxlKmyxil3VveHgJnAD9zZEwL4BlKoN5I'
BOT_TOKEN = os.environ.get('BOT_TOKEN')
bot = telebot.TeleBot(BOT_TOKEN)


# api_key = "205b51fa-ec6d-496f-9318-2750166c286a"
# model_key = "1117acb9-2b8e-4b0f-a12f-8d81f0a37909"

# Run the model


def add_watermark(input_image_bytes, watermark_image_path, output_image_path):
    # input_image_bytes = base64.b64decode(input_image_base)
    url = watermark_image_path
    response = requests.get(url)
    data = response.content
    # image_encoded = data.encode('utf-8')
    image_bytes = BytesIO(data)
    base_image = Image.open(input_image_bytes)
    watermark = Image.open(image_bytes)
    if watermark.mode != 'RGBA':
        alpha = Image.new('L', watermark.size, 255)
        watermark.putalpha(alpha)

    # Image.Image.paste(base_image, img2, (0, 0))
    # paste_mask = watermark.split()[3].point(lambda i: i * 65 / 100.)
    base_image.paste(watermark, (0, 0), mask=watermark)
    # base_image.save('outputttt.png')
    return base_image


@bot.message_handler(commands=['start'])
def send_welcome(message):
    msg = """
What can this bot do?

Waifu is a cutting-edge website that utilizes advanced AI technology to generate stunning and unique anime girl images. With our platform, you can easily create your very own anime girl character with just a text. 

To use me in your personal group, add me @waifu_arb_bot as an ADMIN in your group. 

How to use it?

>> Use /waifu followed by your attributes of your waifu
    """
    previous_msg = bot.reply_to(message, text=msg,)
@bot.message_handler(commands=['waifu'])
def send_anime(message):
    try:
        # print(message.chat.id)
        # member = bot.get_chat_member(-1001194266290, message.from_user.id)
        # if member.status == 'left':
        #     print('cant')
        #     return
        text = message.text.replace('/waifu', '')
        # print(message.from_user.id)
        previous_msg = bot.reply_to(
            message, text='''<a href='tg://user?id={userid}'>{user}</a> - 👧Your Waifu is being generated… Please wait!'''.format(user=message.from_user.first_name, userid=message.from_user.id), parse_mode='HTML')
        print(text)
# an anime girl in dgs illustration style, 8k, highly detailed, shy, , waifu anime style, big boobs, huge boobs, insane boobs, cute face, huge thigs, in bedroom 
        model_inputs = {
            "prompt": 'dreamlikeart ,1girl, in bra, blush face, naughty' +  text +"waifu, huge boobs, huge nipples, big boobs, detailed boobs, intricate, extremely detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, intimidating lighting, incredible art," ,
            "negative_prompt": "out of focus, evil, disfigured, missing limbs, ugly, missing fingers",
            "hf_token": "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",
            "model_id": "dreamlike-art/dreamlike-diffusion-1.0",
            "num_inference_steps": 50,
            "guidance_scale": 7,
            "height": 768,
            "width": 512,
            "strength": 7,
            "seed": random.randint(42, 4294967295),
            "num_images_per_prompt": 1,

        }
        resp = requests.post('https://run.cerebrium.ai/dreambooth-webhook/predict', headers={"Content-Type": "application/json",
                             'Authorization': 'c_api_key-d328536da93744706417', 'Connection': 'keep-alive'}, json=model_inputs)
        data = resp.json()
        image_byte_string = data['images'][0]
        image_encoded = image_byte_string.encode('utf-8')
        image_bytes = BytesIO(base64.b64decode(image_encoded))
        # image = Image.open(image_bytes)
        img = add_watermark(
            image_bytes, 'https://raw.githubusercontent.com/C-A-Y-D-E/universal_bot/main/images/waifu.png', 'output2.jpg')
        # image.save('output1.png')
        bot.delete_message(chat_id=previous_msg.chat.id,
                           message_id=previous_msg.message_id)
        bot.send_photo(chat_id=message.chat.id, photo=img, reply_to_message_id=message.message_id,
                       caption='''
<b>Waifu</b>: <i>{text}</i>
Image generated by <a href='tg://user?id={userid}'>{user}</a> 
<a href='https://t.me/cryptoai_erc'>Join CryptoAI</a> |  <a href='https://crypto-ai.io'>Website</a> |  <a href='https://app.uniswap.org/#/swap?inputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&outputCurrency=0xf36c5f04127f7470834ed6f98bddc1be62aba48d'>Buy</a>
                    '''.format(text=text, user=message.from_user.first_name, userid=message.from_user.id), parse_mode='HTML')
    except:
        print("An exception occurred")


bot.infinity_polling()
